### ISSUE TITLE
Is there any sample?

### ISSUE THREAD

**Issue by LuohuaRain** [BlazorExtensions/Notifications#1]
I am noob, really don't understand how to use this Notifications.

thanks. and I think it's better to update source code to Blazor 0.5.1

**Comment by galvesribeiro** [comment]
@LuohuaRain 

This project isn't complete yet. @vertonghenb is implementing it and will get back to you later on here.

Thanks

**Comment by vertonghenb** [comment]
Readme got updated to see some usages.
