### ISSUE TITLE
Does this support Notification from Backend?

### ISSUE THREAD

**Issue by wangkanai** [BlazorExtensions/Notifications#13]
Or it only support notification from executed from within Blazor WebAssembly?

**Comment by vertonghenb** [comment]
@wangkanai it's basically a wrapper for the HTML5 Notifcations API in the browser so stuff like SignalR is not supported but can be accomplished with custom code.

**Comment by wangkanai** [comment]
@vertonghenb Thank you there, so i would need to use something like [Azure Notification Hubs](https://azure.microsoft.com/en-us/services/notification-hubs/) then.

**Comment by mhardy** [comment]
> but can be accomplished with custom code

Could you elaborate a little on how this could be accomplished with custom code for Blazor Server?
