### ISSUE TITLE
Test project JSInterop.JSException when CreateAsync

### ISSUE THREAD

**Issue by dsanabriav** [BlazorExtensions/Notifications#20]
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1.. See InnerException for more details. ---> System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1. ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.

**Comment by vertonghenb** [comment]
Fixed in the [new version](https://github.com/Append-IT/Blazor.Notifications)
