### ISSUE TITLE
 Could not find 'BlazorExtensions' in 'window'. .Net Core 3.1 

### ISSUE THREAD

**Issue by ClumsyPenguin** [BlazorExtensions/Notifications#21]
Also the Repo itself is updated with fix #14 but the NuGet is not republished with these changes.

I imported the code locally without NuGet package, but i still get this error.

`crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'BlazorExtensions' in 'window'.
      p/<@https://localhost:44364/_framework/blazor.webassembly.js:1:9130
      p@https://localhost:44364/_framework/blazor.webassembly.js:1:9090
      beginInvokeJSFromDotNet/r<@https://localhost:44364/_framework/blazor.webassembly.js:1:9800
      beginInvokeJSFromDotNet@https://localhost:44364/_framework/blazor.webassembly.js:1:9773
      _mono_wasm_invoke_js_marshalled@https://localhost:44364/_framework/wasm/dotnet.3.2.0.js:1:171294
      mono_wasm_invoke_js_marshalled@:wasm-function[54]:0x0
      do_icall@:wasm-function[6049]:0x10f8b1
      do_icall_wrapper@:wasm-function[1896]:0x50b6a
      interp_exec_method@:wasm-function[1120]:0x2588e
      interp_runtime_invoke@:wasm-function[5655]:0xf7391
      mono_jit_runtime_invoke@:wasm-function[5109]:0xddb3d
      do_runtime_invoke@:wasm-function[1410]:0x3ba85
      mono_runtime_invoke_checked@:wasm-function[331]:0x96a2
      mono_runtime_try_invoke_array@:wasm-function[2333]:0x66c26
      ves_icall_InternalInvoke@:wasm-function[4032]:0xb44ff
      ves_icall_InternalInvoke_raw@:wasm-function[4031]:0xb3ffd
      do_icall@:wasm-function[6049]:0x10f8b1
      do_icall_wrapper@:wasm-function[1896]:0x50b6a
      interp_exec_method@:wasm-function[1120]:0x2588e
      interp_runtime_invoke@:wasm-function[5655]:0xf7391
      mono_jit_runtime_invoke@:wasm-function[5109]:0xddb3d
      do_runtime_invoke@:wasm-function[1410]:0x3ba85
      mono_runtime_try_invoke@:wasm-function[418]:0xcfdb
      mono_runtime_invoke@:wasm-function[1610]:0x44b39
      mono_wasm_invoke_method@:wasm-function[4605]:0xca6a7
      Module._mono_wasm_invoke_method@https://localhost:44364/_framework/wasm/dotnet.3.2.0.js:1:195738
      call_method@https://localhost:44364/_framework/wasm/dotnet.3.2.0.js:1:160823
      bind_static_method/<@https://localhost:44364/_framework/wasm/dotnet.3.2.0.js:1:163094
      beginInvokeDotNetFromJS@https://localhost:44364/_framework/blazor.webassembly.js:1:41657
      s@https://localhost:44364/_framework/blazor.webassembly.js:1:8494
      e.invokeMethodAsync@https://localhost:44364/_framework/blazor.webassembly.js:1:9573
      v/</</<@https://localhost:44364/_framework/blazor.webassembly.js:1:34571
      t.dispatchEvent@https://localhost:44364/_framework/blazor.webassembly.js:1:11119
      e/this.eventDelegator</<@https://localhost:44364/_framework/blazor.webassembly.js:1:12033
      e/this.eventDelegator<@https://localhost:44364/_framework/blazor.webassembly.js:1:12057
      u</e.prototype.onGlobalEvent@https://localhost:44364/_framework/blazor.webassembly.js:1:22113`

**Comment by vertonghenb** [comment]
Fixed in the [new version](https://github.com/Append-IT/Blazor.Notifications)
