### ISSUE TITLE
Please merge Pull Request for Preview 4

### ISSUE THREAD

**Issue by endeffects** [BlazorExtensions/Notifications#4]
Would you please merge the pull request for preview 4 See: https://github.com/BlazorExtensions/Notifications/pull/3

**Comment by vertonghenb** [comment]
Done.

**Comment by endeffects** [comment]
@vertonghenb Thanks alot, but could u please also release a new version of the nuget package?

**Comment by vertonghenb** [comment]
@endeffects most of the time @galvesribeiro does the releases.
